#
# set secrets
# chezmoi secret keyring set --service=opencode_litellm_key_home --user="$USER"
# chezmoi secret keyring set --service=opencode_litellm_key_home --user="$USER" --value="hello"
# chezmoi secret keyring get --service=opencode_litellm_key_home --user="$USER"
#
ssh:
  # If true on macOS, include Colima’s SSH config (safe to leave true at work).
  enable_colima_include: true

  # Keys (override here if you use different paths)
  personalKey: "~/.ssh/marvin"
  workKey: "~/.ssh/work"


opencode:
  profiles:
    home:
      baseURL: "http://192.168.1.50:4000/v1"          # ensure /v1 if OpenAI-compatible
      displayName: "LiteLLM (Home)"
      defaultModel: "vertex_ai/gemini-3.1-pro-preview"
      apiKeyService: "litellm_api_key"   # Keychain service name for the API key

    work:
      displayName: "LiteLLM (Work)"
      defaultModel: "vertex_ai/gemini-2.5-flash"
      apiKeyService: "litellm_api_key"
