-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
-- terminal emojis https://gist.github.com/nicolasdao/8f0220d050f585be1b56cc615ef6c12e
return {
  emoji = {
    Anger = "💢",
    Bug = "🐛",
    Dash = "💨",
    EmptyRedCircle = "⭕",
    Poop = "💩",
    PushPin = "📍",
    RedCircle = "🔴",
    Rocket = "🚀",
    OrangeDiamond = "🔶"
  },
	kind = {
		Call = " ",
		Class = " ",
		Color = " ",
		Constant = " ",
		Constructor = " ",
		Container = " ",
		Continue = '→ ',
		Copilot = ' ',
		Codeium = "";
		Declaration = " ",
		Delete = "󰚃 ",
		Enum = " ",
		EnumMember = " ",
		Event = " ",
		Field = " ",
		Function = "󰡱 ",
		Interface = " ",
		Keyword = " ",
		Method = "m ",
		Module = " ",
		Namespace = " ",
        NvimLua = "",
		Operator = " ",
        Path = "ﱮ",
		Property = " ",
		Quit = "󰩈 ",
        Spell = "暈",
		RecentlyUsed = "󱦺 ",
		Reference = " ",
		Snippet = " ",
		Struct = " ",
		Text = "󰊄 ",
        Treesitter = "",
		TypeParameter = " ",
		Unit = " ",
		Unnamed = "󰺴 ",
		Value = " ",
		Variable = " ",
        Zsh = "",
	},
	type = {
		Array = " ",
		Boolean = "󱎅 ",
		NullName = "[] ",
		Number = " ",
		Object = " ",
		String = " ",
	},
	documents = {
		File = " ",
		Files = " ",
		Folder = " ",
		OpenFolder = " ",
	},
	git = {
		Add = " ",
		Diff = " ",
		Ignore = " ",
		Mod = " ",
		Remove = " ",
		Rename = " ",
		Repo = " ",
	},
	ui = {
		ArrowClosed = " ",
		ArrowOpen = " ",
		BigCircle = " ",
		BigUnfilledCircle = " ",
		BookMark = " ",
		Bug = " ",
		Calendar = " ",
		Check = "󰄬 ",
		ChevronRight = "> ",
		Circle = " ",
		Close = " ",
		CloudDownload = " ",
		Code = " ",
		Comment = " ",
		Configuration = " ",
		Dashboard = " ",
		Do = " ",
		Fire = " ",
		Gear = " ",
		History = " ",
		Home = " ",
		Indicator = " ",
		Lightbulb = " ",
		List = " ",
		Lock = " ",
		NewFile = " ",
		Note = "󰎞 ",
		Operator = " ",
		Package = " ",
		Pencil = " ",
		File = " ",
		Project = " ",
		Regex = ' ',
		Search = " ",
		Separator = ' ',
		Extends = '… ',
		SignIn = " ",
		SignOut = " ",
		Table = " ",
		Telescope = " ",
		Test = "󰙨 ",
	},
	diagnostics = {
		Lsp = ' ',
		Error = " ",
		Hint = " ",
		Information = " ",
		Question = " ",
		Warning = " ",
	},
	misc = {
		Robot = "󱨚 ",
		Squirrel = " ",
		Tag = " ",
		Watch = " ",
	},
	dap = {
		Pause = "󰏤 ",
		Play = " ",
		RunLast = "󰘁 ",
		StepBack = " ",
		StepInto = " ",
		StepOut = "󰆸 ",
		StepOver = " ",
		Terminate = "󰅜 ",
	}
}
