theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
scrolloff = 7
bufferline = "always"
shell = ["zsh", "-c"]
# display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.insert]
"C-h" = "move_char_left"
"C-j" = "move_line_down"
"C-k" = "move_line_up"
"C-l" = "move_char_right"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "total-line-numbers", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
